#!/usr/bin/env python
if __name__ == '__main__':
  from distutils.core import setup
  from distutils.extension import Extension
  from Cython.Build import cythonize
  import numpy as np
  import subprocess as sp

  # attempt to get the git hash and a user-friendly description. Store this
  # information in a module named `_version.py`. There are multiple reasons why
  # the below system calls can fail. We may not have `git` installed, we may
  # not have the project saved in a git repository, we may be on Windows...
  try:
    git_hash = sp.check_output(['git', 'rev-parse', 'HEAD'])
    git_hash = git_hash.decode().strip()
  except Exception as exc:
    print('Encountered the following exception when trying to find the '
          'git hash:\n%s' % repr(exc))
    git_hash = 'UNKNOWN'

  try:
    version = sp.check_output(['git', 'describe', '--always', '--dirty'])
    version = version.decode().strip()
  except Exception as exc:
    print('Encountered the following exception when trying to find the '
          'version:\n%s' % repr(exc))
    version = 'UNKNOWN'

  with open('rbf/_version.py', 'w') as f:
    f.write('# generated by setup.py\n')
    f.write('__git_hash__ = "%s"\n' % git_hash)
    f.write('__version__ = "%s"\n' % version)
    
  ext = []
  ext += [Extension(name='rbf.poly',
                    sources=['rbf/poly.pyx'],
                    include_dirs=[np.get_include()])]
  ext += [Extension(name='rbf.sputils',
                    sources=['rbf/sputils.pyx'],
                    include_dirs=[np.get_include()])]
  ext += [Extension(name='rbf.pde.halton',
                    sources=['rbf/pde/halton.pyx'],
                    include_dirs=[np.get_include()])]
  ext += [Extension(name='rbf.pde.geometry',
                    sources=['rbf/pde/geometry.pyx'],
                    include_dirs=[np.get_include()])]
  ext += [Extension(name='rbf.pde.sampling',
                    sources=['rbf/pde/sampling.pyx'],
                    include_dirs=[np.get_include()])]
  ext += [Extension(name='rbf.misc.bspline',
                    sources=['rbf/misc/bspline.pyx'],
                    include_dirs=[np.get_include()])]
  setup(name='RBF',
        version=version,
        description='Package containing the tools necessary for radial basis '
                    'function (RBF) applications',
        author='Trever Hines',
        author_email='treverhines@gmail.com',
        url='www.github.com/treverhines/RBF',
        packages=['rbf', 'rbf.misc', 'rbf.pde'],
        ext_modules=cythonize(ext),
        license='MIT')


